// Copyright 2021 Tencent Inc. All rights reserved.
//
// 微信支付分账API
//
// 微信支付分账API
//
// API version: 0.0.9

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.profitsharing.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** OrderReceiverDetail */
public class OrderReceiverDetail {
  /** 分账金额 说明：分账金额，单位为分，只能为整数，不能超过原订单支付金额及最大分账比例金额 */
  @SerializedName("amount")
  private Long amount;
  /** 分账描述 说明：分账的原因描述，分账账单中需要体现 */
  @SerializedName("description")
  private String description;
  /** 接收方类型 说明：接收方类型 */
  @SerializedName("type")
  private ReceiverType type;
  /**
   * 接收方账号 说明：1、类型是MERCHANT_ID时，是商户号 2、类型是PERSONAL_OPENID时，是个人openid
   * 3、类型是PERSONAL_SUB_OPENID时，是个人sub_openid
   */
  @SerializedName("account")
  private String account;
  /** 分账结果 说明：分账结果 */
  @SerializedName("result")
  private DetailStatus result;
  /** 分账失败原因 说明：分账失败原因，状态为CLOSED时返回 */
  @SerializedName("fail_reason")
  private DetailFailReason failReason;
  /** 分账创建时间 说明：分账创建时间，遵循RFC3339标准格式 */
  @SerializedName("create_time")
  private String createTime;
  /** 分账完成时间 说明：分账完成时间，遵循RFC3339标准格式 */
  @SerializedName("finish_time")
  private String finishTime;
  /** 分账明细单号 说明：微信分账明细单号，每笔分账业务执行的明细单号，可与资金账单对账使用 */
  @SerializedName("detail_id")
  private String detailId;

  public Long getAmount() {
    return amount;
  }

  public void setAmount(Long amount) {
    this.amount = amount;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ReceiverType getType() {
    return type;
  }

  public void setType(ReceiverType type) {
    this.type = type;
  }

  public String getAccount() {
    return account;
  }

  public void setAccount(String account) {
    this.account = account;
  }

  public DetailStatus getResult() {
    return result;
  }

  public void setResult(DetailStatus result) {
    this.result = result;
  }

  public DetailFailReason getFailReason() {
    return failReason;
  }

  public void setFailReason(DetailFailReason failReason) {
    this.failReason = failReason;
  }

  public String getCreateTime() {
    return createTime;
  }

  public void setCreateTime(String createTime) {
    this.createTime = createTime;
  }

  public String getFinishTime() {
    return finishTime;
  }

  public void setFinishTime(String finishTime) {
    this.finishTime = finishTime;
  }

  public String getDetailId() {
    return detailId;
  }

  public void setDetailId(String detailId) {
    this.detailId = detailId;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderReceiverDetail {\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    failReason: ").append(toIndentedString(failReason)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    finishTime: ").append(toIndentedString(finishTime)).append("\n");
    sb.append("    detailId: ").append(toIndentedString(detailId)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
