// Copyright 2021 Tencent Inc. All rights reserved.
//
// 微信支付分账API
//
// 微信支付分账API
//
// API version: 0.0.9

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.profitsharing.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** SplitBillResponse */
public class SplitBillResponse {
  /** 哈希类型 说明：原始账单（gzip需要解压缩）的摘要算法，用于校验文件的完整性 */
  @SerializedName("hash_type")
  private SplitBillHashType hashType;
  /** 哈希值 说明：原始账单（gzip需要解压缩）的摘要值，用于校验文件的完整性 */
  @SerializedName("hash_value")
  private String hashValue;
  /** 下载地址 说明：供下一步请求账单文件的下载地址，该地址30s内有效 */
  @SerializedName("download_url")
  private String downloadUrl;

  public SplitBillHashType getHashType() {
    return hashType;
  }

  public void setHashType(SplitBillHashType hashType) {
    this.hashType = hashType;
  }

  public String getHashValue() {
    return hashValue;
  }

  public void setHashValue(String hashValue) {
    this.hashValue = hashValue;
  }

  public String getDownloadUrl() {
    return downloadUrl;
  }

  public void setDownloadUrl(String downloadUrl) {
    this.downloadUrl = downloadUrl;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SplitBillResponse {\n");
    sb.append("    hashType: ").append(toIndentedString(hashType)).append("\n");
    sb.append("    hashValue: ").append(toIndentedString(hashValue)).append("\n");
    sb.append("    downloadUrl: ").append(toIndentedString(downloadUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
