// Copyright 2021 Tencent Inc. All rights reserved.
//
// 连锁加盟供应链分账API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 1.0.12

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.brandprofitsharing.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;
import java.util.List;

/** CreateOrderResponse */
public class CreateOrderResponse {
  /** 品牌主商户号 说明：品牌主商户号，微信支付分配的商户号。 */
  @SerializedName("brand_mchid")
  private String brandMchid;
  /** 子商户号 说明：订单收款方商户号，可以是品牌主商户号，也可以是门店商户号，微信支付分配的商户号。 */
  @SerializedName("sub_mchid")
  private String subMchid;
  /** 微信订单号 说明：微信支付订单号 */
  @SerializedName("transaction_id")
  private String transactionId;
  /**
   * 商户分账单号 说明：商户系统内部的分账单号，在商户系统内部唯一（单次分账、多次分账、完结分账应使用不同的商户分账单号），同一分账单号多次请求等同一次，只能是数字、大小写字母_-|*@。
   */
  @SerializedName("out_order_no")
  private String outOrderNo;
  /** 微信分账单号 说明：微信分账单号，微信系统返回的唯一标识 */
  @SerializedName("order_id")
  private String orderId;
  /** 分账接收方列表 说明：分账接收方列表 */
  @SerializedName("receivers")
  private List<ReceiverResultEntity> receivers;
  /** 分账单状态 说明：分账单状态（每个接收方的分账结果请查看receivers中的result字段） */
  @SerializedName("status")
  private SplitOrderStatus status;

  public String getBrandMchid() {
    return brandMchid;
  }

  public void setBrandMchid(String brandMchid) {
    this.brandMchid = brandMchid;
  }

  public String getSubMchid() {
    return subMchid;
  }

  public void setSubMchid(String subMchid) {
    this.subMchid = subMchid;
  }

  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }

  public String getOutOrderNo() {
    return outOrderNo;
  }

  public void setOutOrderNo(String outOrderNo) {
    this.outOrderNo = outOrderNo;
  }

  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public List<ReceiverResultEntity> getReceivers() {
    return receivers;
  }

  public void setReceivers(List<ReceiverResultEntity> receivers) {
    this.receivers = receivers;
  }

  public SplitOrderStatus getStatus() {
    return status;
  }

  public void setStatus(SplitOrderStatus status) {
    this.status = status;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateOrderResponse {\n");
    sb.append("    brandMchid: ").append(toIndentedString(brandMchid)).append("\n");
    sb.append("    subMchid: ").append(toIndentedString(subMchid)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    outOrderNo: ").append(toIndentedString(outOrderNo)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    receivers: ").append(toIndentedString(receivers)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
