// Copyright 2021 Tencent Inc. All rights reserved.
//
// 连锁加盟供应链分账API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 1.0.12

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.brandprofitsharing.model;

import com.google.gson.annotations.SerializedName;

/** SplitOrderStatus */
public enum SplitOrderStatus {
  @SerializedName("PROCESSING")
  PROCESSING,

  @SerializedName("FINISHED")
  FINISHED
}
