// Copyright 2021 Tencent Inc. All rights reserved.
//
// 支付分授权对外API
//
// 支付分授权领域对外API
//
// API version: 1.4.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.payscore.permission.model;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
import com.wechat.pay.java.core.util.GsonUtil;

/** GetPermissionsByAuthorizationCodeRequest */
public class GetPermissionsByAuthorizationCodeRequest {
  /** 服务ID 说明：该服务ID有本接口对应产品的权限。 */
  @SerializedName("service_id")
  @Expose(serialize = false)
  private String serviceId;
  /** 授权协议号 说明：预授权成功时的授权协议号 */
  @SerializedName("authorization_code")
  @Expose(serialize = false)
  private String authorizationCode;

  public String getServiceId() {
    return serviceId;
  }

  public void setServiceId(String serviceId) {
    this.serviceId = serviceId;
  }

  public String getAuthorizationCode() {
    return authorizationCode;
  }

  public void setAuthorizationCode(String authorizationCode) {
    this.authorizationCode = authorizationCode;
  }

  @Override
  public String toString() {
    return GsonUtil.getGson().toJson(this);
  }
}
