// Copyright 2021 Tencent Inc. All rights reserved.
//
// 支付分授权对外API
//
// 支付分授权领域对外API
//
// API version: 1.4.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.payscore.permission.model;

import com.google.gson.annotations.SerializedName;
import com.wechat.pay.java.core.util.GsonUtil;

/** SceneApplyPermissionsRequest */
public class SceneApplyPermissionsRequest {
  /** 服务ID 说明：该服务ID有本接口对应产品的权限. */
  @SerializedName("service_id")
  private String serviceId;
  /** 公众号ID 说明：微信公众平台分配的与传入的商户号建立了支付绑定关系的AppID，可在公众平台查看绑定关系，此参数需在本系统先进行配置。 */
  @SerializedName("appid")
  private String appid;
  /** 授权协议号 说明：要求此参数只能由数字、大小写字母_-|*组成，且在同一个商户号下唯一。详见[商户订单号]。 */
  @SerializedName("authorization_code")
  private String authorizationCode;
  /** 通知地址 说明：授权通知地址 */
  @SerializedName("notify_url")
  private String notifyUrl;
  /** 授权场景 说明：TRANSACTION:微信支付交易中授权 */
  @SerializedName("scene")
  private PermissionsScene scene;
  /** 微信支付交易中授权附带的参数 说明：当Scene为TRANSACTION时填写 */
  @SerializedName("transaction_scene_info")
  private TransactionSceneInfo transactionSceneInfo;

  public String getServiceId() {
    return serviceId;
  }

  public void setServiceId(String serviceId) {
    this.serviceId = serviceId;
  }

  public String getAppid() {
    return appid;
  }

  public void setAppid(String appid) {
    this.appid = appid;
  }

  public String getAuthorizationCode() {
    return authorizationCode;
  }

  public void setAuthorizationCode(String authorizationCode) {
    this.authorizationCode = authorizationCode;
  }

  public String getNotifyUrl() {
    return notifyUrl;
  }

  public void setNotifyUrl(String notifyUrl) {
    this.notifyUrl = notifyUrl;
  }

  public PermissionsScene getScene() {
    return scene;
  }

  public void setScene(PermissionsScene scene) {
    this.scene = scene;
  }

  public TransactionSceneInfo getTransactionSceneInfo() {
    return transactionSceneInfo;
  }

  public void setTransactionSceneInfo(TransactionSceneInfo transactionSceneInfo) {
    this.transactionSceneInfo = transactionSceneInfo;
  }

  @Override
  public String toString() {
    return GsonUtil.getGson().toJson(this);
  }
}
