// Copyright 2021 Tencent Inc. All rights reserved.
//
// APP支付
//
// APP支付API
//
// API version: 1.2.3

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.ecommercecombinepayments.order.model;

import com.google.gson.annotations.SerializedName;


/** TransactionPayer */
public class TransactionPayer {

  @SerializedName("openid")
  private String openid;

  public String getOpenid() {
    return openid;
  }

  public void setOpenid(String openid) {
    this.openid = openid;
  }

  @Override
  public String toString() {
    return "CombinePayerInfo{" +
        "openid='" + openid + '\'' +
        '}';
  }

}
