// Copyright 2021 Tencent Inc. All rights reserved.
//
// 支付分对外API
//
// 包含通用化api及先享后付api
//
// API version: 1.6.3

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.payscore.serviceorder.model;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
import com.wechat.pay.java.core.util.GsonUtil;

/** CancelServiceOrderRequest */
public class CancelServiceOrderRequest {
  /** 商户服务订单号 说明：商户系统内部服务订单号（不是交易单号） */
  @SerializedName("out_order_no")
  @Expose(serialize = false)
  private String outOrderNo;
  /** 公众账号ID 说明：微信公众平台分配的与传入的商户号建立了支付绑定关系的appid，可在公众平台查看绑定关系 需要在本系统先进行配置. 需要与创建订单时保持一致. */
  @SerializedName("appid")
  private String appid;
  /** 服务ID 说明：该服务ID有本接口对应产品的权限 */
  @SerializedName("service_id")
  private String serviceId;
  /** 撤销原因 说明：支持50个字符，按照字符计算 超过长度报错处理 */
  @SerializedName("reason")
  private String reason;
  /** 商户号 说明：直连商户号：平台商必填 */
  @SerializedName("mchid")
  private String mchid;

  public String getOutOrderNo() {
    return outOrderNo;
  }

  public void setOutOrderNo(String outOrderNo) {
    this.outOrderNo = outOrderNo;
  }

  public String getAppid() {
    return appid;
  }

  public void setAppid(String appid) {
    this.appid = appid;
  }

  public String getServiceId() {
    return serviceId;
  }

  public void setServiceId(String serviceId) {
    this.serviceId = serviceId;
  }

  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public String getMchid() {
    return mchid;
  }

  public void setMchid(String mchid) {
    this.mchid = mchid;
  }

  @Override
  public String toString() {
    return GsonUtil.getGson().toJson(this);
  }
}
