// Copyright 2021 Tencent Inc. All rights reserved.
//
// 支付分对外API
//
// 包含通用化api及先享后付api
//
// API version: 1.6.3

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.payscore.serviceorder.model;

import com.google.gson.annotations.SerializedName;
import com.wechat.pay.java.core.util.GsonUtil;

/** 创建订单接口： 1. name是选填； 2. 若name非空： amount和description，二者必须填其一，也可同时填写； 完结订单接口： 1. name和amount是必填； */
public class Payment {
  /** 付费名称 说明：不超过20个字符，超出报错处理 */
  @SerializedName("name")
  private String name;
  /** 付费金额 说明：此付费项目总金额，大于等于0，单位为分，等于0时代表不需要扣费 */
  @SerializedName("amount")
  private Long amount;
  /** 付费说明 说明：描述计费规则，不超过30个字符，超出报错处理 */
  @SerializedName("description")
  private String description;
  /** 付费数量 说明：付费项目的数量 */
  @SerializedName("count")
  private Integer count;

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Long getAmount() {
    return amount;
  }

  public void setAmount(Long amount) {
    this.amount = amount;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  @Override
  public String toString() {
    return GsonUtil.getGson().toJson(this);
  }
}
