// Copyright 2021 Tencent Inc. All rights reserved.
//
// 支付分对外API
//
// 包含通用化api及先享后付api
//
// API version: 1.6.3

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.payscore.serviceorder.model;

import com.google.gson.annotations.SerializedName;
import com.wechat.pay.java.core.util.GsonUtil;
import java.util.List;

/** PromotionDetail */
public class PromotionDetail {
  /** 券ID 说明：券ID */
  @SerializedName("coupon_id")
  private String couponId;
  /** 优惠名称 说明：优惠名称 */
  @SerializedName("name")
  private String name;
  /** 优惠范围 说明：GLOBAL：全场代金券；SINGLE：单品优惠 */
  @SerializedName("scope")
  private String scope;
  /** 优惠类型 说明：CASH：充值；NOCASH：免充值。 */
  @SerializedName("type")
  private String type;
  /** 优惠券面额 说明：优惠券面额 */
  @SerializedName("amount")
  private Long amount;
  /** 活动ID 说明：活动ID，批次ID */
  @SerializedName("stock_id")
  private String stockId;
  /** 微信出资 说明：微信出资 */
  @SerializedName("wechatpay_contribute")
  private Long wechatpayContribute;
  /** 商户出资 说明：商户出资 */
  @SerializedName("merchant_contribute")
  private Long merchantContribute;
  /** 其他出资 说明：其他出资 */
  @SerializedName("other_contribute")
  private Long otherContribute;
  /** 优惠币种 说明：CNY：人民币，境内商户号仅支持人民币 */
  @SerializedName("currency")
  private String currency;
  /** 单品列表 说明：单品列表 */
  @SerializedName("goods_detail")
  private List<GoodsDetail> goodsDetail;

  public String getCouponId() {
    return couponId;
  }

  public void setCouponId(String couponId) {
    this.couponId = couponId;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getScope() {
    return scope;
  }

  public void setScope(String scope) {
    this.scope = scope;
  }

  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Long getAmount() {
    return amount;
  }

  public void setAmount(Long amount) {
    this.amount = amount;
  }

  public String getStockId() {
    return stockId;
  }

  public void setStockId(String stockId) {
    this.stockId = stockId;
  }

  public Long getWechatpayContribute() {
    return wechatpayContribute;
  }

  public void setWechatpayContribute(Long wechatpayContribute) {
    this.wechatpayContribute = wechatpayContribute;
  }

  public Long getMerchantContribute() {
    return merchantContribute;
  }

  public void setMerchantContribute(Long merchantContribute) {
    this.merchantContribute = merchantContribute;
  }

  public Long getOtherContribute() {
    return otherContribute;
  }

  public void setOtherContribute(Long otherContribute) {
    this.otherContribute = otherContribute;
  }

  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public List<GoodsDetail> getGoodsDetail() {
    return goodsDetail;
  }

  public void setGoodsDetail(List<GoodsDetail> goodsDetail) {
    this.goodsDetail = goodsDetail;
  }

  @Override
  public String toString() {
    return GsonUtil.getGson().toJson(this);
  }
}
