// Copyright 2021 Tencent Inc. All rights reserved.
//
// 支付分对外API
//
// 包含通用化api及先享后付api
//
// API version: 1.6.3

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.payscore.serviceorder.model;

import com.google.gson.annotations.SerializedName;
import com.wechat.pay.java.core.util.GsonUtil;
import java.util.List;

/** ServiceOrderEntity */
public class ServiceOrderEntity {
  /** 商户服务订单号 说明：调用接口传入的商户订单号 */
  @SerializedName("out_order_no")
  private String outOrderNo;
  /** 服务ID 说明：调用接口传入的服务ID */
  @SerializedName("service_id")
  private String serviceId;
  /** 服务商公众号ID 说明：调用接口传入的服务商公众号ID */
  @SerializedName("appid")
  private String appid;
  /** 服务商商户号 说明：调用接口传入的服务商商户号 */
  @SerializedName("mchid")
  private String mchid;
  /** 子商户公众号ID 说明：调用接口传入的子商户公众号ID */
  @SerializedName("sub_appid")
  private String subAppid;
  /** 子商户商户号 说明：调用接口传入的子商户商户号 */
  @SerializedName("sub_mchid")
  private String subMchid;
  /** 服务信息 说明：调用接口传入的服务信息 */
  @SerializedName("service_introduction")
  private String serviceIntroduction;
  /**
   * 服务订单状态 说明：当前单据状态. * CREATED: 服务订单已创建 * DOING: 服务订单进行中 * DONE: 服务订单已完成 * REVOKED: 商户取消服务订单 *
   * EXPIRED: 服务订单已失效，\"CREATED\"状态超过1小时未变动，则订单失效
   */
  @SerializedName("state")
  private String state;
  /** 订单状态说明 说明：对服务订单\"DOING\"状态的附加说明. * USER_CONFIRM: 用户确认 * MCH_COMPLETE：商户完结 */
  @SerializedName("state_description")
  private String stateDescription;
  /** 后付费项目 说明：调用接口传入的后付费项目 */
  @SerializedName("post_payments")
  private List<Payment> postPayments;
  /** 商户优惠 说明：调用接口传入的商户优惠 */
  @SerializedName("post_discounts")
  private List<ServiceOrderCoupon> postDiscounts;
  /** 总金额 说明：调用接口传入的总金额 */
  @SerializedName("total_amount")
  private Long totalAmount;
  /** 是否需要收款 说明：调用接口传入的是否需要收款 */
  @SerializedName("need_collection")
  private Boolean needCollection;
  /** 附加数据 说明：调用接口传入的附加数据 */
  @SerializedName("attach")
  private String attach;
  /** 商户回调地址 说明：调用接口传入的商户回调地址 */
  @SerializedName("notify_url")
  private String notifyUrl;
  /** 服务商公众号下的用户标识 说明：调用接口传入的服务商公众号下的用户标识 */
  @SerializedName("openid")
  private String openid;
  /** 子商户公众号下的用户标识 说明：调用接口传入的子商户公众号下的用户标识 */
  @SerializedName("sub_openid")
  private String subOpenid;
  /** 微信支付服务订单号 说明：微信支付服务订单号，每个微信支付服务订单号与商户号下对应的商户服务订单号一一对应 */
  @SerializedName("order_id")
  private String orderId;
  /** 渠道商商户号 说明：渠道商商户号 */
  @SerializedName("channel_id")
  private String channelId;
  /** 收款信息 说明：收款成功后，展示具体的收款信息 */
  @SerializedName("collection")
  private Collection collection;
  /** 服务位置 说明：调用接口传入的服务位置 */
  @SerializedName("location")
  private Location location;
  /** 服务风险金 说明：调用接口传入的服务风险金 */
  @SerializedName("risk_fund")
  private RiskFund riskFund;
  /** 服务时间 说明：调用接口传入的服务时间 */
  @SerializedName("time_range")
  private TimeRange timeRange;

  public String getOutOrderNo() {
    return outOrderNo;
  }

  public void setOutOrderNo(String outOrderNo) {
    this.outOrderNo = outOrderNo;
  }

  public String getServiceId() {
    return serviceId;
  }

  public void setServiceId(String serviceId) {
    this.serviceId = serviceId;
  }

  public String getAppid() {
    return appid;
  }

  public void setAppid(String appid) {
    this.appid = appid;
  }

  public String getMchid() {
    return mchid;
  }

  public void setMchid(String mchid) {
    this.mchid = mchid;
  }

  public String getSubAppid() {
    return subAppid;
  }

  public void setSubAppid(String subAppid) {
    this.subAppid = subAppid;
  }

  public String getSubMchid() {
    return subMchid;
  }

  public void setSubMchid(String subMchid) {
    this.subMchid = subMchid;
  }

  public String getServiceIntroduction() {
    return serviceIntroduction;
  }

  public void setServiceIntroduction(String serviceIntroduction) {
    this.serviceIntroduction = serviceIntroduction;
  }

  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public String getStateDescription() {
    return stateDescription;
  }

  public void setStateDescription(String stateDescription) {
    this.stateDescription = stateDescription;
  }

  public List<Payment> getPostPayments() {
    return postPayments;
  }

  public void setPostPayments(List<Payment> postPayments) {
    this.postPayments = postPayments;
  }

  public List<ServiceOrderCoupon> getPostDiscounts() {
    return postDiscounts;
  }

  public void setPostDiscounts(List<ServiceOrderCoupon> postDiscounts) {
    this.postDiscounts = postDiscounts;
  }

  public Long getTotalAmount() {
    return totalAmount;
  }

  public void setTotalAmount(Long totalAmount) {
    this.totalAmount = totalAmount;
  }

  public Boolean getNeedCollection() {
    return needCollection;
  }

  public void setNeedCollection(Boolean needCollection) {
    this.needCollection = needCollection;
  }

  public String getAttach() {
    return attach;
  }

  public void setAttach(String attach) {
    this.attach = attach;
  }

  public String getNotifyUrl() {
    return notifyUrl;
  }

  public void setNotifyUrl(String notifyUrl) {
    this.notifyUrl = notifyUrl;
  }

  public String getOpenid() {
    return openid;
  }

  public void setOpenid(String openid) {
    this.openid = openid;
  }

  public String getSubOpenid() {
    return subOpenid;
  }

  public void setSubOpenid(String subOpenid) {
    this.subOpenid = subOpenid;
  }

  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public String getChannelId() {
    return channelId;
  }

  public void setChannelId(String channelId) {
    this.channelId = channelId;
  }

  public Collection getCollection() {
    return collection;
  }

  public void setCollection(Collection collection) {
    this.collection = collection;
  }

  public Location getLocation() {
    return location;
  }

  public void setLocation(Location location) {
    this.location = location;
  }

  public RiskFund getRiskFund() {
    return riskFund;
  }

  public void setRiskFund(RiskFund riskFund) {
    this.riskFund = riskFund;
  }

  public TimeRange getTimeRange() {
    return timeRange;
  }

  public void setTimeRange(TimeRange timeRange) {
    this.timeRange = timeRange;
  }

  @Override
  public String toString() {
    return GsonUtil.getGson().toJson(this);
  }
}
