// Copyright 2021 Tencent Inc. All rights reserved.
//
// 支付分对外API
//
// 包含通用化api及先享后付api
//
// API version: 1.6.3

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.payscore.serviceorder.model;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
import com.wechat.pay.java.core.util.GsonUtil;

/** SyncServiceOrderRequest */
public class SyncServiceOrderRequest {
  /** 商户服务订单号 说明：商户系统内部订单号（不是交易单号），要求32个字符内，只能是数字、大小写字母_-|* 且在同一个商户号下唯一。详见商户订单号 需要和创建订单的商户服务订单号一致 */
  @SerializedName("out_order_no")
  @Expose(serialize = false)
  private String outOrderNo;
  /** 公众账号ID 说明：微信公众平台分配的与传入的商户号建立了支付绑定关系的appid，可在公众平台查看绑定关系 需要在本系统先进行配置. 需要与创建订单时保持一致. */
  @SerializedName("appid")
  private String appid;
  /** 服务ID 说明：该服务ID有本接口对应产品的权限 需要与创建订单时保持一致 */
  @SerializedName("service_id")
  private String serviceId;
  /** 场景类型 说明：场景类型- \"Order_Paid\"：字符串表示“订单收款成功” 场景类型- \"Order_Paying\": 字符串表示“订单收款同步” */
  @SerializedName("type")
  private String type;
  /** 商户号 说明：直连商户号：平台商必填 */
  @SerializedName("mchid")
  private String mchid;
  /** 内容信息详情 说明：场景类型为：Order_Paid 时，为必填项； */
  @SerializedName("detail")
  private SyncDetail detail;

  public String getOutOrderNo() {
    return outOrderNo;
  }

  public void setOutOrderNo(String outOrderNo) {
    this.outOrderNo = outOrderNo;
  }

  public String getAppid() {
    return appid;
  }

  public void setAppid(String appid) {
    this.appid = appid;
  }

  public String getServiceId() {
    return serviceId;
  }

  public void setServiceId(String serviceId) {
    this.serviceId = serviceId;
  }

  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public String getMchid() {
    return mchid;
  }

  public void setMchid(String mchid) {
    this.mchid = mchid;
  }

  public SyncDetail getDetail() {
    return detail;
  }

  public void setDetail(SyncDetail detail) {
    this.detail = detail;
  }

  @Override
  public String toString() {
    return GsonUtil.getGson().toJson(this);
  }
}
