// Copyright 2021 Tencent Inc. All rights reserved.
//
// 爱心餐对外API
//
// 微信支付爱心餐公益计划旨在面向深圳市的市政一线环卫工人提供每周一餐的1分钱用餐公益服务。在受助端，微信支付联动上千家餐饮门店关爱特殊人群，通过微信支付数字化能力将人群身份认证与公益福利领用全流程线上化，实现公益福利精准到人。在捐赠端，微信支付发挥连接优势与平台能力，结合用户就餐场景通过爱心餐一块捐插件让用户可在点餐时顺手捐1元，带动更多社会力量致谢城市美容师。
//
// API version: 0.0.4

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.lovefeast.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** Amount */
public class Amount {
  /** 总金额 说明：订单总金额，单位为分。 */
  @SerializedName("total")
  private Integer total;
  /** 用户支付金额 说明：用户支付金额，单位为分。 */
  @SerializedName("payer_total")
  private Integer payerTotal;
  /** 货币类型 说明：CNY：人民币，境内商户号仅支持人民币。 */
  @SerializedName("currency")
  private String currency;
  /** 用户支付币种 说明：用户支付币种 */
  @SerializedName("payer_currency")
  private String payerCurrency;

  public Integer getTotal() {
    return total;
  }

  public void setTotal(Integer total) {
    this.total = total;
  }

  public Integer getPayerTotal() {
    return payerTotal;
  }

  public void setPayerTotal(Integer payerTotal) {
    this.payerTotal = payerTotal;
  }

  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public String getPayerCurrency() {
    return payerCurrency;
  }

  public void setPayerCurrency(String payerCurrency) {
    this.payerCurrency = payerCurrency;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Amount {\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    payerTotal: ").append(toIndentedString(payerTotal)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    payerCurrency: ").append(toIndentedString(payerCurrency)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
