// Copyright 2021 Tencent Inc. All rights reserved.
//
// 爱心餐对外API
//
// 微信支付爱心餐公益计划旨在面向深圳市的市政一线环卫工人提供每周一餐的1分钱用餐公益服务。在受助端，微信支付联动上千家餐饮门店关爱特殊人群，通过微信支付数字化能力将人群身份认证与公益福利领用全流程线上化，实现公益福利精准到人。在捐赠端，微信支付发挥连接优势与平台能力，结合用户就餐场景通过爱心餐一块捐插件让用户可在点餐时顺手捐1元，带动更多社会力量致谢城市美容师。
//
// API version: 0.0.4

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.lovefeast.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** Payer */
public class Payer {
  /** 用户标识 说明：用户在AppID下的唯一标识。在【一块捐】场景下按照商家下单时AppID生成；在【一起捐】场景下按照商户登记AppID生成。 */
  @SerializedName("openid")
  private String openid;
  /** 用户子标识 说明：用户在子AppID下的唯一标识。在【一块捐】场景下按照商家下单时子AppID生成；在【一起捐】场景下按照商户登记子AppID生成。 */
  @SerializedName("sub_openid")
  private String subOpenid;
  /** 用户头像 说明：用户在爱心餐小程序授权头像的URL */
  @SerializedName("avatar")
  private String avatar;
  /** 用户昵称 说明：用户在爱心餐小程序授权昵称 */
  @SerializedName("nickname")
  private String nickname;

  public String getOpenid() {
    return openid;
  }

  public void setOpenid(String openid) {
    this.openid = openid;
  }

  public String getSubOpenid() {
    return subOpenid;
  }

  public void setSubOpenid(String subOpenid) {
    this.subOpenid = subOpenid;
  }

  public String getAvatar() {
    return avatar;
  }

  public void setAvatar(String avatar) {
    this.avatar = avatar;
  }

  public String getNickname() {
    return nickname;
  }

  public void setNickname(String nickname) {
    this.nickname = nickname;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Payer {\n");
    sb.append("    openid: ").append(toIndentedString(openid)).append("\n");
    sb.append("    subOpenid: ").append(toIndentedString(subOpenid)).append("\n");
    sb.append("    avatar: ").append(toIndentedString(avatar)).append("\n");
    sb.append("    nickname: ").append(toIndentedString(nickname)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
