// Copyright 2021 Tencent Inc. All rights reserved.
//
// 营销加价购对外API
//
// 指定服务商可通过该接口报名加价购活动、查询某个区域内的加价购活动列表、锁定加价活动购资格以及解锁加价购活动资格。
//
// API version: 1.4.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.retailstore.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;
import java.util.List;

/** ApplyActivityResponse */
public class ApplyActivityResponse {
  /** 返回结果文案 说明：返回结果文案 */
  @SerializedName("return_message")
  private String returnMessage;
  /** 失败的报名记录 说明：失败的报名记录 */
  @SerializedName("failed_apply_infos")
  private List<ActApplyInfo> failedApplyInfos;
  /** 成功的报名记录 说明：成功的报名记录 */
  @SerializedName("succeed_apply_infos")
  private List<ActApplyInfo> succeedApplyInfos;

  public String getReturnMessage() {
    return returnMessage;
  }

  public void setReturnMessage(String returnMessage) {
    this.returnMessage = returnMessage;
  }

  public List<ActApplyInfo> getFailedApplyInfos() {
    return failedApplyInfos;
  }

  public void setFailedApplyInfos(List<ActApplyInfo> failedApplyInfos) {
    this.failedApplyInfos = failedApplyInfos;
  }

  public List<ActApplyInfo> getSucceedApplyInfos() {
    return succeedApplyInfos;
  }

  public void setSucceedApplyInfos(List<ActApplyInfo> succeedApplyInfos) {
    this.succeedApplyInfos = succeedApplyInfos;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApplyActivityResponse {\n");
    sb.append("    returnMessage: ").append(toIndentedString(returnMessage)).append("\n");
    sb.append("    failedApplyInfos: ").append(toIndentedString(failedApplyInfos)).append("\n");
    sb.append("    succeedApplyInfos: ").append(toIndentedString(succeedApplyInfos)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
