// Copyright 2021 Tencent Inc. All rights reserved.
//
// 营销加价购对外API
//
// 指定服务商可通过该接口报名加价购活动、查询某个区域内的加价购活动列表、锁定加价活动购资格以及解锁加价购活动资格。
//
// API version: 1.4.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.retailstore.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;
import java.util.List;

/** ApplyActivityBody */
public class ApplyActivityBody {
  /** 调用报名活动API的商户的商户号 说明：调用报名活动API的商户的商户号 */
  @SerializedName("caller_merchant_id")
  private String callerMerchantId;
  /** 门店报名信息 说明：门店报名信息 */
  @SerializedName("apply_infos")
  private List<ActApplyInfo> applyInfos;

  public String getCallerMerchantId() {
    return callerMerchantId;
  }

  public void setCallerMerchantId(String callerMerchantId) {
    this.callerMerchantId = callerMerchantId;
  }

  public List<ActApplyInfo> getApplyInfos() {
    return applyInfos;
  }

  public void setApplyInfos(List<ActApplyInfo> applyInfos) {
    this.applyInfos = applyInfos;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApplyActivityBody {\n");
    sb.append("    callerMerchantId: ").append(toIndentedString(callerMerchantId)).append("\n");
    sb.append("    applyInfos: ").append(toIndentedString(applyInfos)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
