// Copyright 2021 Tencent Inc. All rights reserved.
//
// 营销加价购对外API
//
// 指定服务商可通过该接口报名加价购活动、查询某个区域内的加价购活动列表、锁定加价活动购资格以及解锁加价购活动资格。
//
// API version: 1.4.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.retailstore.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** MaterialInfo */
public class MaterialInfo {
  /** 物料码ID 说明：物料码ID */
  @SerializedName("material_id")
  private String materialId;
  /** 物料码链接 说明：物料码链接, 用于生成活动物料二维码 */
  @SerializedName("material_url")
  private String materialUrl;

  public String getMaterialId() {
    return materialId;
  }

  public void setMaterialId(String materialId) {
    this.materialId = materialId;
  }

  public String getMaterialUrl() {
    return materialUrl;
  }

  public void setMaterialUrl(String materialUrl) {
    this.materialUrl = materialUrl;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MaterialInfo {\n");
    sb.append("    materialId: ").append(toIndentedString(materialId)).append("\n");
    sb.append("    materialUrl: ").append(toIndentedString(materialUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
