// Copyright 2021 Tencent Inc. All rights reserved.
//
// 营销加价购对外API
//
// 指定服务商可通过该接口报名加价购活动、查询某个区域内的加价购活动列表、锁定加价活动购资格以及解锁加价购活动资格。
//
// API version: 1.4.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.retailstore.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;
import java.util.List;

/** UnlockQualificationRequest */
public class UnlockQualificationRequest {
  /** 订单信息 说明：订单信息 */
  @SerializedName("order_information")
  private OrderInfo orderInformation;
  /** 待锁定的加价购资格ID列表 说明：待锁定的加价购资格ID列表 */
  @SerializedName("qualification_ids")
  private List<String> qualificationIds;

  public OrderInfo getOrderInformation() {
    return orderInformation;
  }

  public void setOrderInformation(OrderInfo orderInformation) {
    this.orderInformation = orderInformation;
  }

  public List<String> getQualificationIds() {
    return qualificationIds;
  }

  public void setQualificationIds(List<String> qualificationIds) {
    this.qualificationIds = qualificationIds;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UnlockQualificationRequest {\n");
    sb.append("    orderInformation: ").append(toIndentedString(orderInformation)).append("\n");
    sb.append("    qualificationIds: ").append(toIndentedString(qualificationIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
