// Copyright 2021 Tencent Inc. All rights reserved.
//
// 公共出行平台代扣服务对外API
//
// 公共出行平台代扣服务对外API
//
// API version: 1.1.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.weixinpayscanandride.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** CreatePalmPayTransactionRequest */
public class CreatePalmPayTransactionRequest {
  /** 公众账号ID 说明：商户在微信申请公众号或移动应用成功后分配的账号ID，登录平台为mp.weixin.qq.com或open.weixin.qq.com */
  @SerializedName("appid")
  private String appid;
  /** 服务描述 说明：商户自定义字段，用于交易账单中对扣费服务的描述。该字段长度限制为字节长度限制 */
  @SerializedName("description")
  private String description;
  /** 附加数据 说明：附加数据，在查询API和支付通知中原样返回，可作为自定义参数使用，该字段长度限制为字节长度限制 */
  @SerializedName("attach")
  private String attach;
  /** 商户订单号 说明：商户系统内部订单号，只能是数字、大小写字母，且在同一个商户号下唯一。该字段长度限制为字节长度限制 */
  @SerializedName("out_trade_no")
  private String outTradeNo;
  /** 订单优惠标记 说明：代金券或立减优惠功能的参数，说明详见代金券或立减优惠 */
  @SerializedName("goods_tag")
  private String goodsTag;
  /** 签约模板ID 说明：该模板ID是商户在向微信支付提权限申请时由微信支付生成 */
  @SerializedName("plan_id")
  private String planId;
  /** 用户标识 说明：用户在商户AppID下的唯一标识。 */
  @SerializedName("openid")
  private String openid;
  /** 通知地址 说明：接受扣款结果异步回调通知的URL，注意回调URL只接受HTTPS */
  @SerializedName("notify_url")
  private String notifyUrl;
  /** 交易场景 说明：交易场景值，目前支持 ：PALM_METRO—刷掌地铁； */
  @SerializedName("trade_scene")
  private PalmPayTradeScene tradeScene;
  /** 地铁场景信息 说明：请求受理扣费 tradescene为PALM_METRO时，传入该参数 */
  @SerializedName("metro_info")
  private PalmMetroSceneInfo metroInfo;
  /** 订单金额 说明：订单金额 */
  @SerializedName("amount")
  private OrderAmount amount;

  public String getAppid() {
    return appid;
  }

  public void setAppid(String appid) {
    this.appid = appid;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getAttach() {
    return attach;
  }

  public void setAttach(String attach) {
    this.attach = attach;
  }

  public String getOutTradeNo() {
    return outTradeNo;
  }

  public void setOutTradeNo(String outTradeNo) {
    this.outTradeNo = outTradeNo;
  }

  public String getGoodsTag() {
    return goodsTag;
  }

  public void setGoodsTag(String goodsTag) {
    this.goodsTag = goodsTag;
  }

  public String getPlanId() {
    return planId;
  }

  public void setPlanId(String planId) {
    this.planId = planId;
  }

  public String getOpenid() {
    return openid;
  }

  public void setOpenid(String openid) {
    this.openid = openid;
  }

  public String getNotifyUrl() {
    return notifyUrl;
  }

  public void setNotifyUrl(String notifyUrl) {
    this.notifyUrl = notifyUrl;
  }

  public PalmPayTradeScene getTradeScene() {
    return tradeScene;
  }

  public void setTradeScene(PalmPayTradeScene tradeScene) {
    this.tradeScene = tradeScene;
  }

  public PalmMetroSceneInfo getMetroInfo() {
    return metroInfo;
  }

  public void setMetroInfo(PalmMetroSceneInfo metroInfo) {
    this.metroInfo = metroInfo;
  }

  public OrderAmount getAmount() {
    return amount;
  }

  public void setAmount(OrderAmount amount) {
    this.amount = amount;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreatePalmPayTransactionRequest {\n");
    sb.append("    appid: ").append(toIndentedString(appid)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    attach: ").append(toIndentedString(attach)).append("\n");
    sb.append("    outTradeNo: ").append(toIndentedString(outTradeNo)).append("\n");
    sb.append("    goodsTag: ").append(toIndentedString(goodsTag)).append("\n");
    sb.append("    planId: ").append(toIndentedString(planId)).append("\n");
    sb.append("    openid: ").append(toIndentedString(openid)).append("\n");
    sb.append("    notifyUrl: ").append(toIndentedString(notifyUrl)).append("\n");
    sb.append("    tradeScene: ").append(toIndentedString(tradeScene)).append("\n");
    sb.append("    metroInfo: ").append(toIndentedString(metroInfo)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
