// Copyright 2021 Tencent Inc. All rights reserved.
//
// 支付有礼活动对外API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.1.2

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.giftactivity.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
import java.util.ArrayList;
import java.util.List;

/** AddActivityMerchantRequest */
public class AddActivityMerchantRequest {
  /** 活动Id 说明：活动Id */
  @SerializedName("activity_id")
  @Expose(serialize = false)
  private String activityId;
  /** 添加的发券商户号 说明：新增到活动中的发券商户号列表 */
  @SerializedName("merchant_id_list")
  private List<String> merchantIdList = new ArrayList<String>();
  /** 请求业务单据号 说明：商户添加发券商户号的凭据号，商户侧需保持唯一性 */
  @SerializedName("add_request_no")
  private String addRequestNo;

  public String getActivityId() {
    return activityId;
  }

  public void setActivityId(String activityId) {
    this.activityId = activityId;
  }

  public List<String> getMerchantIdList() {
    return merchantIdList;
  }

  public void setMerchantIdList(List<String> merchantIdList) {
    this.merchantIdList = merchantIdList;
  }

  public String getAddRequestNo() {
    return addRequestNo;
  }

  public void setAddRequestNo(String addRequestNo) {
    this.addRequestNo = addRequestNo;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddActivityMerchantRequest {\n");
    sb.append("    activityId: ").append(toIndentedString(activityId)).append("\n");
    sb.append("    merchantIdList: ").append(toIndentedString(merchantIdList)).append("\n");
    sb.append("    addRequestNo: ").append(toIndentedString(addRequestNo)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
