// Copyright 2021 Tencent Inc. All rights reserved.
//
// 支付有礼活动对外API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.1.2

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.giftactivity.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;
import java.util.ArrayList;
import java.util.List;

/** DeleteActivityMerchantBody */
public class DeleteActivityMerchantBody {
  /** 删除的发券商户号 说明：从活动已有的发券商户号中移除的商户号列表 */
  @SerializedName("merchant_id_list")
  private List<String> merchantIdList = new ArrayList<String>();
  /** 请求业务单据号 说明：商户添加发券商户号的凭据号，商户侧需保持唯一性 */
  @SerializedName("delete_request_no")
  private String deleteRequestNo;

  public List<String> getMerchantIdList() {
    return merchantIdList;
  }

  public void setMerchantIdList(List<String> merchantIdList) {
    this.merchantIdList = merchantIdList;
  }

  public String getDeleteRequestNo() {
    return deleteRequestNo;
  }

  public void setDeleteRequestNo(String deleteRequestNo) {
    this.deleteRequestNo = deleteRequestNo;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteActivityMerchantBody {\n");
    sb.append("    merchantIdList: ").append(toIndentedString(merchantIdList)).append("\n");
    sb.append("    deleteRequestNo: ").append(toIndentedString(deleteRequestNo)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
