// Copyright 2021 Tencent Inc. All rights reserved.
//
// 支付有礼活动对外API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.1.2

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.giftactivity.model;

import com.google.gson.annotations.SerializedName;

/** 投放目的枚举值 */
public enum DeliveryPurposeCategory {
  @SerializedName("OFF_LINE_PAY")
  OFF_LINE_PAY,

  @SerializedName("JUMP_MINI_APP")
  JUMP_MINI_APP
}
