// Copyright 2021 Tencent Inc. All rights reserved.
//
// 支付有礼活动对外API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.1.2

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.giftactivity.model;

import com.google.gson.annotations.SerializedName;

/** ParticipateMchStatus */
public enum ParticipateMchStatus {
  @SerializedName("PARTIC_MCH_STATUS_INVALID")
  PARTIC_MCH_STATUS_INVALID,

  @SerializedName("PARTIC_MCH_STATUS_VALID")
  PARTIC_MCH_STATUS_VALID,

  @SerializedName("PARTIC_MCH_STATUS_EXPIRE")
  PARTIC_MCH_STATUS_EXPIRE
}
