// Copyright 2021 Tencent Inc. All rights reserved.
//
// 支付有礼活动对外API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.1.2

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.giftactivity.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** PaymentMethodInfo */
public class PaymentMethodInfo {
  /** 支付方式 说明：支付方式，可以指定银行卡或零钱 */
  @SerializedName("payment_method")
  private PaymentMethodCategory paymentMethod;
  /** 银行简称 说明：银行简称，指定支付方式为银行卡必填，详询附录 */
  @SerializedName("bank_abbreviation")
  private String bankAbbreviation;

  public PaymentMethodCategory getPaymentMethod() {
    return paymentMethod;
  }

  public void setPaymentMethod(PaymentMethodCategory paymentMethod) {
    this.paymentMethod = paymentMethod;
  }

  public String getBankAbbreviation() {
    return bankAbbreviation;
  }

  public void setBankAbbreviation(String bankAbbreviation) {
    this.bankAbbreviation = bankAbbreviation;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentMethodInfo {\n");
    sb.append("    paymentMethod: ").append(toIndentedString(paymentMethod)).append("\n");
    sb.append("    bankAbbreviation: ").append(toIndentedString(bankAbbreviation)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
