// Copyright 2021 Tencent Inc. All rights reserved.
//
// APP支付
//
// APP支付API
//
// API version: 1.2.3

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.payment.app.model;

import com.google.gson.annotations.SerializedName;
import com.wechat.pay.java.core.util.GsonUtil;

/** 支付场景描述 */
public class SceneInfo {
  /** 用户终端IP 说明：用户终端IP */
  @SerializedName("payer_client_ip")
  private String payerClientIp;
  /** 商户端设备号 说明：商户端设备号 */
  @SerializedName("device_id")
  private String deviceId;
  /** storeInfo */
  @SerializedName("store_info")
  private StoreInfo storeInfo;

  public String getPayerClientIp() {
    return payerClientIp;
  }

  public void setPayerClientIp(String payerClientIp) {
    this.payerClientIp = payerClientIp;
  }

  public String getDeviceId() {
    return deviceId;
  }

  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }

  public StoreInfo getStoreInfo() {
    return storeInfo;
  }

  public void setStoreInfo(StoreInfo storeInfo) {
    this.storeInfo = storeInfo;
  }

  @Override
  public String toString() {
    return GsonUtil.getGson().toJson(this);
  }
}
