// Copyright 2021 Tencent Inc. All rights reserved.
//
// 境内普通商户退款API
//
// 境内普通商户退款功能涉及的API文档
//
// API version: 1.2.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.refund.model;

import com.google.gson.annotations.SerializedName;

/**
 * ORIGINAL - 原路退款，退款渠道 BALANCE - 退回到余额，退款渠道 OTHER_BALANCE - 原账户异常退到其他余额账户，退款渠道 OTHER_BANKCARD -
 * 原银行卡异常退到其他银行卡，退款渠道
 */
public enum Channel {
  @SerializedName("ORIGINAL")
  ORIGINAL,

  @SerializedName("BALANCE")
  BALANCE,

  @SerializedName("OTHER_BALANCE")
  OTHER_BALANCE,

  @SerializedName("OTHER_BANKCARD")
  OTHER_BANKCARD
}
