// Copyright 2021 Tencent Inc. All rights reserved.
//
// 商家转账对外API（2025年1月15日升级版本）
//
// 申请电子回单
// [https://pay.weixin.qq.com/doc/v3/merchant/4012716456](https://pay.weixin.qq.com/doc/v3/merchant/4012716456)
// 商户可以 通过该接口申请 商家转账用户确认模式转账单据 对应的电子回单。
// 微信支付会在校验满足回单申请条件后受理回单的申请，商户后续可以通过电子回单查询接口查询回单处理进度。
// 申请回单前，请先确认是否满足回单申请的条件，不满足回单申请条件时，多次重试申请无意义：
// 1. 仅支持付款成功的转账单据申请电子回单.
// 2. 仅支持传入姓名的转账单据申请电子回单.
// 3. 仅支持六个月内的转账单据申请电子回单.
// 回单申请完成后的有效期为90天，过期后需要重新申请。受理成功不表示回单一定能成功生成，以查单结果返回为准。
//
// API version: 1.0.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.mchtransfer.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** AcceptElecsignResponse */
public class AcceptElecsignResponse {
  /**
   * 【申请单状态】 GENERATING：生成中，FINISHED: 已完成，FAILED: 已失败
   *
   * <ul>
   *   <li><code>GENERATING</code>: 表示当前电子回单已受理成功并在处理中
   *   <li><code>FINISHED</code>: 表示当前电子回单已处理完成
   *   <li><code>FAILED</code>: 表示当前电子回单生成失败，失败原因字段会返回具体的失败原因
   * </ul>
   */
  @SerializedName("state")
  private String state;

  /** 【申请单创建时间】 申请单的创建时间，按照使用rfc3339所定义的格式，格式为yyyy-MM-DDThh:mm:ss+TIMEZONE */
  @SerializedName("create_time")
  private String createTime;

  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public String getCreateTime() {
    return createTime;
  }

  public void setCreateTime(String createTime) {
    this.createTime = createTime;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AcceptElecsignResponse {\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
