// Copyright 2021 Tencent Inc. All rights reserved.
//
// 商家转账对外API（2025年1月15日升级版本）
//
// 申请电子回单
// [https://pay.weixin.qq.com/doc/v3/merchant/4012716456](https://pay.weixin.qq.com/doc/v3/merchant/4012716456)
// 商户可以 通过该接口申请 商家转账用户确认模式转账单据 对应的电子回单。
// 微信支付会在校验满足回单申请条件后受理回单的申请，商户后续可以通过电子回单查询接口查询回单处理进度。
// 申请回单前，请先确认是否满足回单申请的条件，不满足回单申请条件时，多次重试申请无意义：
// 1. 仅支持付款成功的转账单据申请电子回单.
// 2. 仅支持传入姓名的转账单据申请电子回单.
// 3. 仅支持六个月内的转账单据申请电子回单.
// 回单申请完成后的有效期为90天，过期后需要重新申请。受理成功不表示回单一定能成功生成，以查单结果返回为准。
//
// API version: 1.0.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.mchtransfer.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** AcceptElecsignByOutNoRequest */
public class AcceptElecsignByOutNoRequest {
  /** 【商户转账单号】 商户创建转账单据使用的单号 */
  @SerializedName("out_bill_no")
  private String outBillNo;

  public String getOutBillNo() {
    return outBillNo;
  }

  public void setOutBillNo(String outBillNo) {
    this.outBillNo = outBillNo;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AcceptElecsignByOutNoRequest {\n");
    sb.append("    outBillNo: ").append(toIndentedString(outBillNo)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
