// Copyright 2021 Tencent Inc. All rights reserved.
//
// 商家转账对外API（2025年1月15日升级版本）
//
// 查询电子回单
// [https://pay.weixin.qq.com/doc/v3/merchant/4012716455](https://pay.weixin.qq.com/doc/v3/merchant/4012716455)
// 商户可以通过该接口查看回单申请进度
// 回单状态            含义                                         建议处理方式
// GENERATING         表示电子回单正在生成中                          过段时间重试查询，建议查询时间间隔不低于2分钟
// FINISHED           回单已成功生成，会返回回单文件的下载地址和摘要信息    通过返回的下载地址下载回单文件数据并比较摘要值
// FAILED             电子回单生成失败，会返回具体的失败原因             停止重试查询，查看具体的失败原因
// 请务必对比下载的回单文件的摘要值与查询接口返回的摘要值的一致性，确保得到的回单文件的真实性和完整性。
// 下载地址的有效期为10分钟，超过10分钟后需要重新通过该接口获取下载地址（不需要重新申请）。
//
// API version: 1.0.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.mchtransfer.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** QueryElecsignByOutNoRequest */
public class QueryElecsignByOutNoRequest {
  /** 【商户转账单号】 商户创建转账单据使用的单号 */
  @SerializedName("out_bill_no")
  private String outBillNo;

  public String getOutBillNo() {
    return outBillNo;
  }

  public void setOutBillNo(String outBillNo) {
    this.outBillNo = outBillNo;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryElecsignByOutNoRequest {\n");
    sb.append("    outBillNo: ").append(toIndentedString(outBillNo)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
