// Copyright 2021 Tencent Inc. All rights reserved.
//
// 营销商家券对外API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.0.11

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.merchantexclusivecoupon.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** CouponCodeInfoResponse */
public class CouponCodeInfoResponse {
  /** 商户上传code信息 说明：商户上传code信息，含状态，上传时间等 */
  @SerializedName("code_information")
  private CouponCodeEntity codeInformation;
  /** 用户券信息 说明：用户券信息，仅当商户上传code的状态为DISPATCHED时返回券详情 */
  @SerializedName("coupon_information")
  private CouponEntity couponInformation;

  public CouponCodeEntity getCodeInformation() {
    return codeInformation;
  }

  public void setCodeInformation(CouponCodeEntity codeInformation) {
    this.codeInformation = codeInformation;
  }

  public CouponEntity getCouponInformation() {
    return couponInformation;
  }

  public void setCouponInformation(CouponEntity couponInformation) {
    this.couponInformation = couponInformation;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CouponCodeInfoResponse {\n");
    sb.append("    codeInformation: ").append(toIndentedString(codeInformation)).append("\n");
    sb.append("    couponInformation: ").append(toIndentedString(couponInformation)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
