// Copyright 2021 Tencent Inc. All rights reserved.
//
// 营销商家券对外API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.0.11

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.merchantexclusivecoupon.model;

import com.google.gson.annotations.SerializedName;

/** CouponUseMethod */
public enum CouponUseMethod {
  @SerializedName("OFF_LINE")
  OFF_LINE,

  @SerializedName("MINI_PROGRAMS")
  MINI_PROGRAMS,

  @SerializedName("SELF_CONSUME")
  SELF_CONSUME,

  @SerializedName("PAYMENT_CODE")
  PAYMENT_CODE
}
