// Copyright 2021 Tencent Inc. All rights reserved.
//
// 营销商家券对外API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.0.11

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.merchantexclusivecoupon.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** DeactivateCouponRequest */
public class DeactivateCouponRequest {
  /** 券code 说明：券的唯一标识 */
  @SerializedName("coupon_code")
  private String couponCode;
  /** 批次号 说明：券的所属批次号 */
  @SerializedName("stock_id")
  private String stockId;
  /** 失效请求单据号 说明：每次失效请求的唯一标识，商户需保证唯一 */
  @SerializedName("deactivate_request_no")
  private String deactivateRequestNo;
  /** 失效原因 说明：商户失效券的原因 */
  @SerializedName("deactivate_reason")
  private String deactivateReason;

  public String getCouponCode() {
    return couponCode;
  }

  public void setCouponCode(String couponCode) {
    this.couponCode = couponCode;
  }

  public String getStockId() {
    return stockId;
  }

  public void setStockId(String stockId) {
    this.stockId = stockId;
  }

  public String getDeactivateRequestNo() {
    return deactivateRequestNo;
  }

  public void setDeactivateRequestNo(String deactivateRequestNo) {
    this.deactivateRequestNo = deactivateRequestNo;
  }

  public String getDeactivateReason() {
    return deactivateReason;
  }

  public void setDeactivateReason(String deactivateReason) {
    this.deactivateReason = deactivateReason;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeactivateCouponRequest {\n");
    sb.append("    couponCode: ").append(toIndentedString(couponCode)).append("\n");
    sb.append("    stockId: ").append(toIndentedString(stockId)).append("\n");
    sb.append("    deactivateRequestNo: ")
        .append(toIndentedString(deactivateRequestNo))
        .append("\n");
    sb.append("    deactivateReason: ").append(toIndentedString(deactivateReason)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
