// Copyright 2021 Tencent Inc. All rights reserved.
//
// 营销商家券对外API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.0.11

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.merchantexclusivecoupon.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** ModifyCouponUseRule */
public class ModifyCouponUseRule {
  /** 核销方式 说明：核销方式 */
  @SerializedName("use_method")
  private CouponUseMethod useMethod;
  /** 小程序AppID 说明：核销方式为线上小程序核销才有效 */
  @SerializedName("mini_programs_appid")
  private String miniProgramsAppid;
  /** 小程序path 说明：核销方式为线上小程序核销才有效 */
  @SerializedName("mini_programs_path")
  private String miniProgramsPath;

  public CouponUseMethod getUseMethod() {
    return useMethod;
  }

  public void setUseMethod(CouponUseMethod useMethod) {
    this.useMethod = useMethod;
  }

  public String getMiniProgramsAppid() {
    return miniProgramsAppid;
  }

  public void setMiniProgramsAppid(String miniProgramsAppid) {
    this.miniProgramsAppid = miniProgramsAppid;
  }

  public String getMiniProgramsPath() {
    return miniProgramsPath;
  }

  public void setMiniProgramsPath(String miniProgramsPath) {
    this.miniProgramsPath = miniProgramsPath;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModifyCouponUseRule {\n");
    sb.append("    useMethod: ").append(toIndentedString(useMethod)).append("\n");
    sb.append("    miniProgramsAppid: ").append(toIndentedString(miniProgramsAppid)).append("\n");
    sb.append("    miniProgramsPath: ").append(toIndentedString(miniProgramsPath)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
