// Copyright 2021 Tencent Inc. All rights reserved.
//
// 营销商家券对外API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.0.11

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.merchantexclusivecoupon.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/** PayReceiptInfoRequest */
public class PayReceiptInfoRequest {
  /** 补差付款单号 说明：补差付款唯一单号，由微信支付生成，仅在补差付款成功后有返回 */
  @SerializedName("subsidy_receipt_id")
  @Expose(serialize = false)
  private String subsidyReceiptId;

  public String getSubsidyReceiptId() {
    return subsidyReceiptId;
  }

  public void setSubsidyReceiptId(String subsidyReceiptId) {
    this.subsidyReceiptId = subsidyReceiptId;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayReceiptInfoRequest {\n");
    sb.append("    subsidyReceiptId: ").append(toIndentedString(subsidyReceiptId)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
