// Copyright 2021 Tencent Inc. All rights reserved.
//
// 营销商家券对外API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.0.11

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.merchantexclusivecoupon.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** StockGetResponse */
public class StockGetResponse {
  /** 商家券批次名称 说明：批次名称，字数上限为21个，一个中文汉字/英文字母/数字均占用一个字数。 */
  @SerializedName("stock_name")
  private String stockName;
  /** 批次归属商户号 说明：批次是归属于哪个商户 注： 普通直连模式，该参数为直连商户号； 服务商模式，该参数为子商户号； 间连模式，该参数为子商户号。 */
  @SerializedName("belong_merchant")
  private String belongMerchant;
  /** 批次备注 说明：仅配置商户可见，用于自定义信息。字数上限为20个，一个中文汉字/英文字母/数字均占用一个字数。 */
  @SerializedName("comment")
  private String comment;
  /** 适应商品范围 说明：用来描述批次在哪些商品可用，会显示在微信卡包中。字数上限为15个，一个中文汉字/英文字母/数字均占用一个字数。 */
  @SerializedName("goods_name")
  private String goodsName;
  /** 批次类型 说明：批次类型 */
  @SerializedName("stock_type")
  private BusiFavorStockType stockType;
  /** 核销规则 说明：核销规则 */
  @SerializedName("coupon_use_rule")
  private CouponUseRule couponUseRule;
  /** 发放规则 说明：发放规则 */
  @SerializedName("stock_send_rule")
  private StockSendRule stockSendRule;
  /** 自定义入口 说明：卡详情页面，可选择多种入口引导用户 */
  @SerializedName("custom_entrance")
  private CustomEntrance customEntrance;
  /** 样式信息 说明：创建批次时的样式信息 */
  @SerializedName("display_pattern_info")
  private DisplayPatternInfo displayPatternInfo;
  /** 批次状态 说明：批次状态 */
  @SerializedName("stock_state")
  private StockStatus stockState;
  /** 券code模式 说明：券code模式 */
  @SerializedName("coupon_code_mode")
  private CouponCodeMode couponCodeMode;
  /** 批次号 说明：批次唯一标识 */
  @SerializedName("stock_id")
  private String stockId;
  /**
   * 券code数量
   * 说明：当且仅当coupon_code_mode(券code模式)为MERCHANT_UPLOAD(商户上传自定义code)模式时，返回该字段；返回内容为商户上传code的数量信息
   */
  @SerializedName("coupon_code_count")
  private CouponCodeCount couponCodeCount;
  /** 事件通知配置 说明：事件回调通知商户的配置 */
  @SerializedName("notify_config")
  private NotifyConfig notifyConfig;
  /** 批次发放情况 说明：批次发放情况 */
  @SerializedName("send_count_information")
  private SendCount sendCountInformation;
  /** 是否允许营销补差 说明：该批次发放的券是否允许进行补差 注：该字段暂未开放 */
  @SerializedName("subsidy")
  private Boolean subsidy;

  public String getStockName() {
    return stockName;
  }

  public void setStockName(String stockName) {
    this.stockName = stockName;
  }

  public String getBelongMerchant() {
    return belongMerchant;
  }

  public void setBelongMerchant(String belongMerchant) {
    this.belongMerchant = belongMerchant;
  }

  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public String getGoodsName() {
    return goodsName;
  }

  public void setGoodsName(String goodsName) {
    this.goodsName = goodsName;
  }

  public BusiFavorStockType getStockType() {
    return stockType;
  }

  public void setStockType(BusiFavorStockType stockType) {
    this.stockType = stockType;
  }

  public CouponUseRule getCouponUseRule() {
    return couponUseRule;
  }

  public void setCouponUseRule(CouponUseRule couponUseRule) {
    this.couponUseRule = couponUseRule;
  }

  public StockSendRule getStockSendRule() {
    return stockSendRule;
  }

  public void setStockSendRule(StockSendRule stockSendRule) {
    this.stockSendRule = stockSendRule;
  }

  public CustomEntrance getCustomEntrance() {
    return customEntrance;
  }

  public void setCustomEntrance(CustomEntrance customEntrance) {
    this.customEntrance = customEntrance;
  }

  public DisplayPatternInfo getDisplayPatternInfo() {
    return displayPatternInfo;
  }

  public void setDisplayPatternInfo(DisplayPatternInfo displayPatternInfo) {
    this.displayPatternInfo = displayPatternInfo;
  }

  public StockStatus getStockState() {
    return stockState;
  }

  public void setStockState(StockStatus stockState) {
    this.stockState = stockState;
  }

  public CouponCodeMode getCouponCodeMode() {
    return couponCodeMode;
  }

  public void setCouponCodeMode(CouponCodeMode couponCodeMode) {
    this.couponCodeMode = couponCodeMode;
  }

  public String getStockId() {
    return stockId;
  }

  public void setStockId(String stockId) {
    this.stockId = stockId;
  }

  public CouponCodeCount getCouponCodeCount() {
    return couponCodeCount;
  }

  public void setCouponCodeCount(CouponCodeCount couponCodeCount) {
    this.couponCodeCount = couponCodeCount;
  }

  public NotifyConfig getNotifyConfig() {
    return notifyConfig;
  }

  public void setNotifyConfig(NotifyConfig notifyConfig) {
    this.notifyConfig = notifyConfig;
  }

  public SendCount getSendCountInformation() {
    return sendCountInformation;
  }

  public void setSendCountInformation(SendCount sendCountInformation) {
    this.sendCountInformation = sendCountInformation;
  }

  public Boolean getSubsidy() {
    return subsidy;
  }

  public void setSubsidy(Boolean subsidy) {
    this.subsidy = subsidy;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StockGetResponse {\n");
    sb.append("    stockName: ").append(toIndentedString(stockName)).append("\n");
    sb.append("    belongMerchant: ").append(toIndentedString(belongMerchant)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    goodsName: ").append(toIndentedString(goodsName)).append("\n");
    sb.append("    stockType: ").append(toIndentedString(stockType)).append("\n");
    sb.append("    couponUseRule: ").append(toIndentedString(couponUseRule)).append("\n");
    sb.append("    stockSendRule: ").append(toIndentedString(stockSendRule)).append("\n");
    sb.append("    customEntrance: ").append(toIndentedString(customEntrance)).append("\n");
    sb.append("    displayPatternInfo: ").append(toIndentedString(displayPatternInfo)).append("\n");
    sb.append("    stockState: ").append(toIndentedString(stockState)).append("\n");
    sb.append("    couponCodeMode: ").append(toIndentedString(couponCodeMode)).append("\n");
    sb.append("    stockId: ").append(toIndentedString(stockId)).append("\n");
    sb.append("    couponCodeCount: ").append(toIndentedString(couponCodeCount)).append("\n");
    sb.append("    notifyConfig: ").append(toIndentedString(notifyConfig)).append("\n");
    sb.append("    sendCountInformation: ")
        .append(toIndentedString(sendCountInformation))
        .append("\n");
    sb.append("    subsidy: ").append(toIndentedString(subsidy)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
