// Copyright 2021 Tencent Inc. All rights reserved.
//
// 营销商家券对外API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.0.11

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.merchantexclusivecoupon.model;

import com.google.gson.annotations.SerializedName;

/** SubsidyPayReceiptStatus */
public enum SubsidyPayReceiptStatus {
  @SerializedName("PAY_RECEIPT_UNKNOWN")
  PAY_RECEIPT_UNKNOWN,

  @SerializedName("PAY_RECEIPT_ACCEPTED")
  PAY_RECEIPT_ACCEPTED,

  @SerializedName("PAY_RECEIPT_SUCCESS")
  PAY_RECEIPT_SUCCESS,

  @SerializedName("PAY_RECEIPT_FAIL")
  PAY_RECEIPT_FAIL,

  @SerializedName("PAY_RECEIPT_RETURNING")
  PAY_RECEIPT_RETURNING,

  @SerializedName("PAY_RECEIPT_PARTIAL_RETURN")
  PAY_RECEIPT_PARTIAL_RETURN,

  @SerializedName("PAY_RECEIPT_FULL_RETURN")
  PAY_RECEIPT_FULL_RETURN
}
