// Copyright 2021 Tencent Inc. All rights reserved.
//
// 营销商家券对外API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.0.11

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.merchantexclusivecoupon.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** SubsidyReturnReceipt */
public class SubsidyReturnReceipt {
  /** 补差回退单号 说明：补差回退唯一单号，由微信支付生成，仅在补差回退成功后有返回 */
  @SerializedName("subsidy_return_receipt_id")
  private String subsidyReturnReceiptId;
  /** 商家券批次号 说明：由微信支付生成，调用创建商家券API成功时返回的唯一批次ID */
  @SerializedName("stock_id")
  private String stockId;
  /** 商家券code 说明：券的唯一标识 */
  @SerializedName("coupon_code")
  private String couponCode;
  /** 微信支付订单号 说明：微信支付下单支付成功返回的订单号 */
  @SerializedName("transaction_id")
  private String transactionId;
  /** 微信支付退款单号 说明：微信支付退款单号 */
  @SerializedName("refund_id")
  private String refundId;
  /** 原营销补差扣款商户号 说明：原营销补差扣款商户号，即回退资金收款商户号 */
  @SerializedName("payer_merchant")
  private String payerMerchant;
  /** 原营销补差入账商户号 说明：原营销补差入账商户号，即回退资金扣款商户号 */
  @SerializedName("payee_merchant")
  private String payeeMerchant;
  /** 补差回退金额 说明：本次补差回退金额，单位为分。单个券code回退总金额不能超过补差金额 */
  @SerializedName("amount")
  private Long amount;
  /** 补差回退描述 说明：回退备注描述，查询的时候原样带回 */
  @SerializedName("description")
  private String description;
  /** 补差回退单据状态 说明：补差付款单据状态 */
  @SerializedName("status")
  private SubsidyReturnReceiptStatus status;
  /** 补差回退失败原因 说明：仅在补差回退失败时，返回告知对应失败的原因 */
  @SerializedName("fail_reason")
  private SubsidyReturnReceiptFailReason failReason;
  /** 补差回退完成时间 说明：仅在补差回退成功时，返回完成时间 */
  @SerializedName("return_done_time")
  private String returnDoneTime;
  /** 补差付款单号 说明：此次补差回退操作对应的补差付款单号 */
  @SerializedName("subsidy_receipt_id")
  private String subsidyReceiptId;
  /** 业务请求唯一单号 说明：商户侧需保证唯一性。可包含英文字母，数字，｜，_，*，-等内容，不允许出现其他不合法符号 */
  @SerializedName("out_subsidy_return_no")
  private String outSubsidyReturnNo;
  /** 补差回退发起时间 说明：补差回退单据创建时间 */
  @SerializedName("return_create_time")
  private String returnCreateTime;

  public String getSubsidyReturnReceiptId() {
    return subsidyReturnReceiptId;
  }

  public void setSubsidyReturnReceiptId(String subsidyReturnReceiptId) {
    this.subsidyReturnReceiptId = subsidyReturnReceiptId;
  }

  public String getStockId() {
    return stockId;
  }

  public void setStockId(String stockId) {
    this.stockId = stockId;
  }

  public String getCouponCode() {
    return couponCode;
  }

  public void setCouponCode(String couponCode) {
    this.couponCode = couponCode;
  }

  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }

  public String getRefundId() {
    return refundId;
  }

  public void setRefundId(String refundId) {
    this.refundId = refundId;
  }

  public String getPayerMerchant() {
    return payerMerchant;
  }

  public void setPayerMerchant(String payerMerchant) {
    this.payerMerchant = payerMerchant;
  }

  public String getPayeeMerchant() {
    return payeeMerchant;
  }

  public void setPayeeMerchant(String payeeMerchant) {
    this.payeeMerchant = payeeMerchant;
  }

  public Long getAmount() {
    return amount;
  }

  public void setAmount(Long amount) {
    this.amount = amount;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public SubsidyReturnReceiptStatus getStatus() {
    return status;
  }

  public void setStatus(SubsidyReturnReceiptStatus status) {
    this.status = status;
  }

  public SubsidyReturnReceiptFailReason getFailReason() {
    return failReason;
  }

  public void setFailReason(SubsidyReturnReceiptFailReason failReason) {
    this.failReason = failReason;
  }

  public String getReturnDoneTime() {
    return returnDoneTime;
  }

  public void setReturnDoneTime(String returnDoneTime) {
    this.returnDoneTime = returnDoneTime;
  }

  public String getSubsidyReceiptId() {
    return subsidyReceiptId;
  }

  public void setSubsidyReceiptId(String subsidyReceiptId) {
    this.subsidyReceiptId = subsidyReceiptId;
  }

  public String getOutSubsidyReturnNo() {
    return outSubsidyReturnNo;
  }

  public void setOutSubsidyReturnNo(String outSubsidyReturnNo) {
    this.outSubsidyReturnNo = outSubsidyReturnNo;
  }

  public String getReturnCreateTime() {
    return returnCreateTime;
  }

  public void setReturnCreateTime(String returnCreateTime) {
    this.returnCreateTime = returnCreateTime;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubsidyReturnReceipt {\n");
    sb.append("    subsidyReturnReceiptId: ")
        .append(toIndentedString(subsidyReturnReceiptId))
        .append("\n");
    sb.append("    stockId: ").append(toIndentedString(stockId)).append("\n");
    sb.append("    couponCode: ").append(toIndentedString(couponCode)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    refundId: ").append(toIndentedString(refundId)).append("\n");
    sb.append("    payerMerchant: ").append(toIndentedString(payerMerchant)).append("\n");
    sb.append("    payeeMerchant: ").append(toIndentedString(payeeMerchant)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    failReason: ").append(toIndentedString(failReason)).append("\n");
    sb.append("    returnDoneTime: ").append(toIndentedString(returnDoneTime)).append("\n");
    sb.append("    subsidyReceiptId: ").append(toIndentedString(subsidyReceiptId)).append("\n");
    sb.append("    outSubsidyReturnNo: ").append(toIndentedString(outSubsidyReturnNo)).append("\n");
    sb.append("    returnCreateTime: ").append(toIndentedString(returnCreateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
