// Copyright 2021 Tencent Inc. All rights reserved.
//
// 微信支付营销系统开放API
//
// 新增立减金api
//
// API version: 3.4.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.cashcoupons.model;

import com.google.gson.annotations.SerializedName;

/** BackgroundColor */
public enum BackgroundColor {
  @SerializedName("COLOR010")
  COLOR010,

  @SerializedName("COLOR020")
  COLOR020,

  @SerializedName("COLOR030")
  COLOR030,

  @SerializedName("COLOR040")
  COLOR040,

  @SerializedName("COLOR050")
  COLOR050,

  @SerializedName("COLOR060")
  COLOR060,

  @SerializedName("COLOR070")
  COLOR070,

  @SerializedName("COLOR080")
  COLOR080,

  @SerializedName("COLOR081")
  COLOR081,

  @SerializedName("COLOR082")
  COLOR082,

  @SerializedName("COLOR090")
  COLOR090,

  @SerializedName("COLOR100")
  COLOR100,

  @SerializedName("COLOR101")
  COLOR101,

  @SerializedName("COLOR102")
  COLOR102
}
