// Copyright 2021 Tencent Inc. All rights reserved.
//
// 微信支付营销系统开放API
//
// 新增立减金api
//
// API version: 3.4.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.cashcoupons.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** FavorAvailableTime */
public class FavorAvailableTime {
  /** 固定时间段可用 说明：固定时间段可用 */
  @SerializedName("fix_available_time")
  private FixedAvailableTime fixAvailableTime;
  /** 领取第二天生效 说明：true-是；false-否 */
  @SerializedName("second_day_available")
  private Boolean secondDayAvailable;
  /** 领取后有效时间 说明：领取后有效时间，单位分钟 */
  @SerializedName("available_time_after_receive")
  private Integer availableTimeAfterReceive;

  public FixedAvailableTime getFixAvailableTime() {
    return fixAvailableTime;
  }

  public void setFixAvailableTime(FixedAvailableTime fixAvailableTime) {
    this.fixAvailableTime = fixAvailableTime;
  }

  public Boolean getSecondDayAvailable() {
    return secondDayAvailable;
  }

  public void setSecondDayAvailable(Boolean secondDayAvailable) {
    this.secondDayAvailable = secondDayAvailable;
  }

  public Integer getAvailableTimeAfterReceive() {
    return availableTimeAfterReceive;
  }

  public void setAvailableTimeAfterReceive(Integer availableTimeAfterReceive) {
    this.availableTimeAfterReceive = availableTimeAfterReceive;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FavorAvailableTime {\n");
    sb.append("    fixAvailableTime: ").append(toIndentedString(fixAvailableTime)).append("\n");
    sb.append("    secondDayAvailable: ").append(toIndentedString(secondDayAvailable)).append("\n");
    sb.append("    availableTimeAfterReceive: ")
        .append(toIndentedString(availableTimeAfterReceive))
        .append("\n");
    sb.append("}");
    return sb.toString();
  }
}
