// Copyright 2021 Tencent Inc. All rights reserved.
//
// 微信支付营销系统开放API
//
// 新增立减金api
//
// API version: 3.4.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.cashcoupons.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** UseFlowResponse */
public class UseFlowResponse {
  /** 下载链接 说明：流水文件下载链接，30s内有效 */
  @SerializedName("url")
  private String url;
  /** 安全校验码 说明：文件内容的哈希值，防止篡改 */
  @SerializedName("hash_value")
  private String hashValue;
  /** 哈希算法类型 说明：哈希算法类型，目前只支持sha1 */
  @SerializedName("hash_type")
  private String hashType;

  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public String getHashValue() {
    return hashValue;
  }

  public void setHashValue(String hashValue) {
    this.hashValue = hashValue;
  }

  public String getHashType() {
    return hashType;
  }

  public void setHashType(String hashType) {
    this.hashType = hashType;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UseFlowResponse {\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    hashValue: ").append(toIndentedString(hashValue)).append("\n");
    sb.append("    hashType: ").append(toIndentedString(hashType)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
